export const FORMAT_OPTIONS = [
  {
    id: "apa",
    name: "APA",
    fullName: "American Psychological Association",
    description: "Social sciences, education, psychology",
    color: "#3B82F6",
    icon: "brain",
  },
  {
    id: "mla",
    name: "MLA",
    fullName: "Modern Language Association",
    description: "Humanities, literature, arts",
    color: "#8B5CF6",
    icon: "book-open",
  },
  {
    id: "chicago",
    name: "Chicago",
    fullName: "Chicago Manual of Style",
    description: "History, publishing, general academic",
    color: "#EF4444",
    icon: "landmark",
  },
  {
    id: "ama",
    name: "AMA",
    fullName: "American Medical Association",
    description: "Medicine, health, biological sciences",
    color: "#10B981",
    icon: "heart-pulse",
  },
  {
    id: "vancouver",
    name: "Vancouver",
    fullName: "Vancouver Style",
    description: "Biomedical journals, clinical research",
    color: "#06B6D4",
    icon: "microscope",
  },
  {
    id: "ieee",
    name: "IEEE",
    fullName: "IEEE Conference Format",
    description: "Engineering, computer science, electronics",
    color: "#F59E0B",
    icon: "cpu",
  },
  {
    id: "harvard",
    name: "Harvard",
    fullName: "Harvard Referencing",
    description: "Business, social sciences, general use",
    color: "#DC2626",
    icon: "graduation-cap",
  },
  {
    id: "acs",
    name: "ACS",
    fullName: "American Chemical Society",
    description: "Chemistry, biochemistry, materials science",
    color: "#7C3AED",
    icon: "flask-conical",
  },
  {
    id: "cse",
    name: "CSE",
    fullName: "Council of Science Editors",
    description: "Biology, earth sciences, natural sciences",
    color: "#059669",
    icon: "leaf",
  },
  {
    id: "custom",
    name: "Custom",
    fullName: "Your Own Format",
    description: "Define your own rules and formatting style",
    color: "#C45D3E",
    icon: "settings",
  },
] as const;

export type FormatId = (typeof FORMAT_OPTIONS)[number]["id"];
